spring:
  application:
    name: oidc-multi-secret-demo
  thymeleaf:
    cache: false
  session:
    timeout: 30m  # 30 minutes inactivity timeout

# Security configuration type
# Options: oidc, basic, none, entra
security:
  type: oidc

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false  # Set to true in production with HTTPS
        same-site: lax
        max-age: 30m  # Cookie expires after 30 minutes

app:
  oidc:
    issuer-uri: https://your-oidc-provider.com
    client-id: your-client-id
    client-secrets:
      - your-first-secret
      - your-second-secret
      - your-third-secret
    redirect-uri: http://localhost:8080/login/oauth2/code/oidc
    scopes:
      - openid
      - profile
      - email
    secret-rotation-interval-ms: 60000  # 1 minute
    authorization-uri: ${app.oidc.issuer-uri}/protocol/openid-connect/auth
    token-uri: ${app.oidc.issuer-uri}/protocol/openid-connect/token
    user-info-uri: ${app.oidc.issuer-uri}/protocol/openid-connect/userinfo
    jwk-set-uri: ${app.oidc.issuer-uri}/protocol/openid-connect/certs
    end-session-uri: ${app.oidc.issuer-uri}/protocol/openid-connect/logout
    post-logout-redirect-uri: http://localhost:8080

logging:
  level:
    com.example.oidc: DEBUG
    com.example.entra: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg [%thread] [correlationId=%X{correlationId:-N/A}] [transactionId=%X{transactionId:-N/A}] %logger{36} - %n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [correlationId=%X{correlationId:-N/A}] [transactionId=%X{transactionId:-N/A}] %-5level %logger{36} - %msg%n"

# Single Page Application (SPA) configuration
spa:
  enabled: false  # Set to true to enable SPA mode
  index-url: index.html  # Can be any filename like: spa-index.html, app.html, angular-app.html
  not-found-url: /not-found?page={notFoundUrl}
  forward-api-requests: false
  exclude-patterns:
    - /api/**
    - /actuator/**
    - /oauth2/**
    - /login/**
    - /logout
    - /error
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.jpg
    - /**/*.jpeg
    - /**/*.gif
    - /**/*.svg
    - /**/*.ico
    - /**/*.woff
    - /**/*.woff2
    - /**/*.ttf
    - /**/*.eot

# Microsoft Entra ID configuration (when security.type=entra)
entra:
  tenant-id: your-azure-tenant-id
  allowed-groups: []  # List of Azure AD group IDs that are allowed access
  allowed-app-roles: []  # List of app roles that are allowed access

# Spring OAuth2 configuration for Entra
# Uncomment and configure when using security.type=entra
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          entra:
#            client-id: your-azure-app-client-id
#            client-secret: your-azure-app-client-secret
#            scope:
#              - openid
#              - profile
#              - email
#              - https://graph.microsoft.com/User.Read
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Microsoft Entra ID
#        provider:
#          entra:
#            issuer-uri: https://login.microsoftonline.com/${entra.tenant-id}/v2.0
#            authorization-uri: https://login.microsoftonline.com/${entra.tenant-id}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${entra.tenant-id}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            jwk-set-uri: https://login.microsoftonline.com/${entra.tenant-id}/discovery/v2.0/keys
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          issuer-uri: https://login.microsoftonline.com/${entra.tenant-id}/v2.0
#          audiences:
#            - your-azure-app-client-id