# Security configuration type for tests
security:
  type: oidc

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://test-issuer.com
        registration:
          oidc:
            client-id: test-client-id
            client-secret: test-secret-1
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

oidc:
  multiple-secrets:
    client-name: oidc
    secrets:
      - test-secret-1
      - test-secret-2
    rotation:
      enabled: true
      interval-ms: 10000